# Generated by Django 4.2.11 on 2024-08-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_add_certificate_and_file_path_on_Filmwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.TextField(choices=[('mail', 'male'), ('female', 'femail')], null=True, verbose_name='gender'),
        ),
    ]
